language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t pushpana/docker-react -f Dockerfile.dev .
build:
  - docker run -e CI=true pushpana/docker-react npm run test
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-333957842689"
  bucket_path: "docker-react"
  on:
     branch: master
     access_key_id: $AWS_ACCESS_KEY
     secret_access_key: $AWS_SECRET_KEY
